- name: Import resource_group
  include_tasks: resource_group.yml
  

- name: Import network
  include_tasks: network.yml  
  tags: 
    - network

- name: Import Public IP
  include_tasks: public_ip.yml
  tags: 
    - pip
  
- name: Import ssh-key
  include_tasks: ssh-key.yml
  tags: 
    - ssh-key

- name: Import instances
  include_tasks: instances.yml
  tags: 
    - instances