- name: Create Public IP  
  delegate_to: localhost
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: Static
    name: "public_ip_{{ item }}"
    domain_name_label: "k8s-{{ item }}-{{ random_suffix }}"
    tags: "{{ tags_kube }}"
  loop: "{{ vm_ids }}"

- name: Get Public IP info
  delegate_to: localhost
  azure.azcollection.azure_rm_publicipaddress_info:
    resource_group: "{{ resource_group }}"
    name: "public_ip_{{ item }}"
  loop: "{{ vm_ids }}"
  register: public_ip_info

- name: Display Public IP addresses
  debug:
    msg: "{{ item.publicipaddresses[0].ip_address }}"
  loop: "{{ public_ip_info.results }}"
