# ============================================================
#  INSTALAÇÃO DE PACOTES BÁSICOS NECESSÁRIOS
# ============================================================
- name: install apps
  ansible.builtin.apt:
    name: "{{ apps_to_install }}"
    state: present
  vars:
    apps_to_install:
      - apt-transport-https      # suporte HTTPS para repositórios apt
      - ca-certificates          # certificados raiz confiáveis
      - curl                     # ferramenta para transferir dados (usada em downloads)
      - gnupg                    # manipulação de chaves GPG
      - lsb-release           
    apt:
      update_cache: yes          # atualiza cache apt antes da instalação


# ============================================================
#  ADIÇÃO DA CHAVE GPG DO DOCKER
# ============================================================
- name: add gpg
  ansible.builtin.shell:
    cmd: "curl -fssl https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg   # evita recriar se já existir


# ============================================================
#  ADIÇÃO DO REPOSITÓRIO DO DOCKER
# ============================================================
- name: add docker repo
  ansible.builtin.shell: 
    cmd: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null


# ============================================================
#  INSTALAÇÃO E CONFIGURAÇÃO DO CONTAINERD
# ============================================================
- name: install containerd
  ansible.builtin.apt:
    name: containerd.io
    state: present
    update_cache: yes    

- name: configure containerd
  ansible.builtin.shell:
    cmd: |
      containerd config default | sudo tee /etc/containerd/config.toml
      sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
      systemctl restart containerd


# ============================================================
#  HABILITAÇÃO DO SERVIÇO KUBELET
# ============================================================
- name: enable kubelet
  ansible.builtin.command: systemctl enable --now kubelet


# ============================================================
#  REINICIALIZAÇÃO DO CLUSTER K8S (CASO JÁ EXISTENTE)
# ============================================================
- name: reset cluster
  command: kubeadm reset --force
  register: kubeadmin_init
  when: force_run | default(false)

# ============================================================
#  INICIALIZAÇÃO DO CLUSTER MESTRE
# ============================================================
- name: init cluster
  shell: sudo kubeadm init --pod-network-cidr=10.10.0.0/16 --apiserver-advertise-address=192.168.1.4
  args:
    creates: /etc/kubernetes/admin.conf   # evita rodar novamente se já inicializado
  register: kubeadmin_result
  
#extrair a linha do join (stdout+stderr)
- name: pegar comando de join (worker) do output do init (se houver)
  ansible.builtin.set_fact:
    join_worker_cmd: >-
      {{ ((kubeadmin_result.stdout | default('')) ~ '\n' ~ (kubeadmin_result.stderr | default('')))
         | regex_search('kubeadm join\\s+[^\\n]+--discovery-token-ca-cert-hash\\s+sha256:[0-9a-f]+', multiline=True)
         | default('') }}

# ============================================================
#  CONFIGURAÇÃO DO KUBECTL PARA O USUÁRIO ROOT
# ============================================================
- name: create .kube dir
  shell: |
    mkdir -p /root/.kube
    cp -f /etc/kubernetes/admin.conf /root/.kube/config
    chown $(id -u):$(id -g) /root/.kube/config
  args:
    creates: /root/.kube/config
    # as duas linhas abaixo são exemplos alternativos
    #sudo cp -i /etc/kubernetes/admin.conf $home/.kube/config
    #sudo chown $(id -u):$(id -g) $home/.kube/config


# ============================================================
#  INSTALAÇÃO DO PLUGIN DE REDE (WEAVE NET)
# ============================================================
- name: install weave net
  shell: |
    kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
  args:
    creates: /etc/cni/net.d/10-weave.conflist   # impede reaplicar se já instalado

  
# ============================================================
#  OBTÉM TOKEN E HASH PARA ADICIONAR WORKERS AO CLUSTER
# ============================================================
- name: clsuter token
  shell: kubeadm token list | cut -d ' ' -f1 | sed -n '2p'
  register: k8s_token

- name: ca hash
  shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: k8s_master_ca_hash
  args:
    creates: /etc/kubernetes/pki/ca.crt   # impede rodar se já existir


# ============================================================
#  CRIA UM HOST TEMPORÁRIO PARA COMPARTILHAR TOKEN E HASH
# ============================================================
- name: adicionando o token e o hash em um dummy host
  add_host:
    name: "k8s_token_holder"
    token: "{{ k8s_token.stdout }}"
    hash: "{{ k8s_master_ca_hash.stdout }}"
    join: "{{ join_worker_cmd }}"
  run_once: true
  delegate_to: localhost


# ============================================================
#  MOSTRA OS VALORES DO TOKEN E HASH (DEBUG)
# ============================================================
- name: token
  debug:
    msg: "[master] k8s_token_holder - o token eh {{ hostvars['k8s_token_holder']['token'] }}"

- name: hash
  debug:
    msg: "[master] k8s_token_holder - o hash eh {{ hostvars['k8s_token_holder']['hash'] }}"

- name: debug
  debug:
    msg: "k8s_token={{ k8s_token.stdout }} k8s_master_ca_hash={{ k8s_master_ca_hash.stdout }}"

# ============================================================
#  VERIFICA SE OS NÓS ESTÃO NO CLUSTER
# ============================================================
- name: tmp
  ansible.builtin.command: kubectl get nodes
  register: result

- name: show result
  ansible.builtin.debug:
    var: result.stdout_lines
