- name: Reset and clean Kubernetes worker
  become: true
  ansible.builtin.shell: |
    kubeadm reset --force
    systemctl stop kubelet || true
    rm -rf /etc/kubernetes /var/lib/kubelet /var/lib/cni /etc/cni/net.d
    systemctl restart containerd || true
  register: reset_worker
  changed_when: true
  #failed_when: reset_worker.rc not in [0]


- name: Joien node to cluster
  ansible.builtin.command:
    argv:
      - kubeadm
      - join
      - "{{ k8s_master_node_ip_private }}:{{ k8s_api_secure_port | default('6443') }}"
      - --token
      - "{{ hostvars['k8s_token_holder']['token'] }}"
      - --discovery-token-ca-cert-hash
      - "sha256:{{ hostvars['k8s_token_holder']['hash'] }}"