- name: token
  debug: 
    msg: "[Master] K8S_TOKEN_HOLDER K8S token is {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"

- name: hash
  debug:
    msg: "[Master] K8S_TOKEN_HOLDER K8S token is {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"

- name: "Kubeadm reset node cluster config"
  command: kubeadm reset --force
  register: kubeadmin-reset_node

- name: "Join node to cluster"
  ansible.builtin.shell:
    cmd: |
      kubeadm join  --token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }} \
      --discovery-token-ca-cert-hash=sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }} \
      {{ K8S_MASTER_NODE_IP }}:{{ K8S_API_SECURE_PORT }}