- name: Create Network interface
  azure.azcollection.azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: "nic_{{ item }}"
    vne
    subnet: "{{ subnet_name }}"
    security_group: "{{ nsg_name }}"
    ip_configurations:
      - name: "ipconfig_{{ item }}"
        public_ip_address_name: "public_ip_{{ item }}"
        private_ip_address_version: IPv4
        private_ip_allocation_method: Dynamic
  register: nic
  loop: "{{ vm_ids }}"

- name: Create instances
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "instance_{{ item }}"
    vm_size: "{{ size_instances }}"
    admin_username: "{{ admin_user }}"
    admin_password: "{{ admin_password }}"
    network_interface_name: "nic_{{ item }}"
    image:
      offer: "{{ os_image_offer }}"
      publisher: "{{ os_image_publisher }}"
      sku: "{{ os_image_sku }}"
      version: latest
    managed_disk_type: "{{ managed_disk_type }}"
  register: vm
  loop: "{{ vm_ids }}"
