- name: Create Network interface
  azure.azcollection.azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: "nic_{{ item }}"
    virtual_network: "{{ vnet_name }}"
    subnet: "{{ subnet_name }}"
    security_group: "{{ nsg_name }}"
    assign_public_ip: yes
  register: nic
  loop: "{{ vm_ids }}"

- name: Create instances
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "instance_{{ item }}"
    vm_size: "{{ size_instances }}"
    admin_username: "{{ admin_user }}"
    admin_password: "{{ admin_password }}"
    network_interface_names: "nic_{{ item }}"
    image:
      offer: "{{ os_image_offer }}"
      publisher: "{{ os_image_publisher }}"
      sku: "{{ os_image_sku }}"
      version: latest
    managed_disk_type: "{{ managed_disk_type }}"
  register: vm
  loop: "{{ vm_ids }}"