- name: Create Network Security Group
  delegate_to: localhost
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ nsg_name }}"
    location: "{{ location }}"
    rules:
      - name: AllowSSH
        protocol: Tcp
        destination_port_range: 22
        source_address_prefix: "*"
        source_port_range: "*"
        access: Allow
        priority: 1000
        direction: Inbound    
    tags: "{{ tags_kube }}"  
  register: nsg

- name: Create virtual network
  delegate_to: localhost
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: "{{ vnet_name }}"
    address_prefixes: "{{ vnet_address_prefix }}"
    tags: "{{ tags_kube }}"
  register: vnet


- name: create subnet
  delegate_to: localhost
  azure.azcollection.azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ subnet_name }}"
    address_prefix_cidr: "{{ subnet_address_prefix }}"
    virtual_network_name: "{{ vnet_name }}"
    security_group: "{{ nsg_name }}"
  register: subnet