- name: Create Public IP  
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: Static
    name: "public_ip_{{ item }}"
    domain_name_label: "k8s-{{ item }}-{{ random_suffix }}"
    tags: 
      Environment: "QA"
      App: Kubernetes
  register: public_ip
  loop: "{{ vm_ids }}"