- name: Create Resrource Group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
    tags: 
      environment: "QA"
      App: Kubernetes
  register: rg