- hosts: all
  become: true
  user: azureuser
  gather_facts: no
  pre_tasks:
    - name: 'install python3'
      raw: 'apt -y install python3'
  roles:
    - install_k8s

- hosts: k8s-master
  become: true
  user: azureuser
  roles:
    - create-cluster

- hosts: k8s-workers
  become: true
  user: azureuser
  roles:
    - join-workers

- hosts: k8s-master
  become: true
  user: azureuser
  roles:
    - install-helm