#SPDX-License-Identifier: MIT-0
---

#Playbook location
playbook_dir:  "/data/Ansible-LinuxTips/Projeto-k8s-cluster/provisioning"

# vars file for create-instances
resource_group : "rg-k8s-cluster"
location : "eastus"
nsg_name : "nsg-k8s-cluster"
vnet_name : "vnet-k8s-cluster"
vnet_address_prefix : "192.168.0.0/16"
subnet_name : "subnet-k8s-cluster"
subnet_address_prefix : "192.168.1.0/24"

#Nics
nic_instance_01 : "nic_instance_01"
nic_instance_02 : "nic_instance_02"
nic_instance_03 : "nic_instance_03"

#Size
size_instances : "Standard_B2s"
os_image_offer : "ubuntu-24_04-lts"
os_image_publisher : "Canonical"
os_image_sku : "server"
managed_disk_type : "StandardSSD_LRS"


#USer
admin_user : "rafaeladmin"
admin_password : "YourP@ssw0rd1234" 

#PIP
public_ip_instance_01 : "pip_instance_01"


#LOOP VMS
vm_ids:
  - 01
  - 02
  - 03