---
- name: Create resource_group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
  delegate_to: localhost
  run_once: true
  register: rg
  tags: k8s_cluster

- name: Create NSG
  delegate_to: localhost
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ nsg_name }}"
    location: "{{ location }}"
    rules:
      - name: AllowSSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound

      - name: AllowK8sAPI
        protocol: Tcp
        destination_port_range: 6443
        access: Allow
        priority: 1002
        direction: Inbound
  register: nsg

- name: Create Virtual Network
  delegate_to: localhost
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: "{{ vnet_name }}"
    address_prefixes: "{{ vnet_address_prefix }}"
    location: "{{ location }}"
    dns_servers: []
  register: vnet

- name: Create a subnet
  delegate_to: localhost
  azure.azcollection.azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ subnet_name }}"
    address_prefix: "{{ subnet_address_prefix }}"
    virtual_network: "{{ vnet_name }}"
    security_group_name : "{{ nsg_name }}"
  register: subnet

